name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
      
jobs:
  build:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test
